### ISSUE TITLE
folder-layout: please move out of top-level jacktrip/ folder

### ISSUE THREAD

**Issue by umlaeute** [jcacerec/jacktrip#18]
after switching to github, it seems that the entire jacktrip project is contained within a `jacktrip/` directory.

since git (unlike svn) doesn't allow to clone a subdirectory of a repository, this means that after a clone i end up with a `jacktrip/jacktrip/` folder for no apparent reason:

    $ git clone https://github.com/jcacerec/jacktrip.git
    $ cd jacktrip
    $ cd jacktrip
    $ cat INSTALL.txt

alternatively, downloading the zip-file for a release yields the same result:

    $ wget https://github.com/jcacerec/jacktrip/archive/v1.1.tar.gz
    $ tar xvzf v1.1.tgz
    $ cd jacktrip-1.1
    $ cd jacktrip
    $ cat INSTALL.txt

The only reason I can guess to keep this layout, is to keep the front-page at github tidy.
however, the inner `jacktrip/` folder only contains 8 items, and github automatically renders any `README.md` file found in the root, so I think that moving everything (but README.md) up one level into `/jacktrip/` would be just as beautiful.

**Comment by jcacerec** [comment]
Layout fixed.
