### ISSUE TITLE
Feature request: option to not connect to default ports

### ISSUE THREAD

**Issue by hugonz** [jcacerec/jacktrip#19]
Hello,

I use jacktrip with gladish as part of a studio for live podcast/radio production with IDJC. I can add jacktrip to my flow, but I have to manually disconnect the default ports even when I save the studio.

The ports I want to connect are always connected, but I always get connections to the default jack capture and output at startup. Could we have a command line option to not connect any ports automatically?

Jacktrip is awesome, thanks!

**Comment by jcacerec** [comment]
Hi, I pushed a commit with that option enabled (--nojackportsconnect). Let me know if it works for you.

**Comment by hugonz** [comment]
I built it and tried it yesterday and it works perfectly. Now I can set up a studio in LADISH and bring it all together and connected, even with jacktrip and other computers. Thanks a lot, Juan Pablo.

Also, jacktrip-git is installable in Arch via the Arch User Repository, an (Internet) friend took care of that a couple days ago.
