### ISSUE TITLE
Installation instructions in INSTALL.txt no longer valid for OSX

### ISSUE THREAD

**Issue by taggalucci** [jcacerec/jacktrip#20]
According to INSTALL.txt:

> $ git clone https://github.com/jcacerec/jacktrip.git
> $ cd jacktrip/jacktrip/src
> $ sudo cp jacktrip /usr/bin/
>  (enter your password when prompted)
>
> $ sudo chmod 755 /usr/bin/jacktrip
>   (now you can run jacktrip from any directory using Terminal)

This suggests that the src folder contains a binary called jacktrip which it doesn't.

Also, when attempting to compile using the following instructions:

> If you're on Mac OS X or Fedora Linux and have all the dependencies installed,
> you can build by simply going to the /src directory and typing the following:
>     ./build

This doesn't work. I get the following:

> clang: warning: no such sysroot directory: 'macosx10.9'
> In file included from DataProtocol.cpp:38:
> ./DataProtocol.h:46:10: fatal error: 'netinet/in.h' file not found
> #include <netinet/in.h> //sockaddr_in{} and other Internet defns
>          ^
> 1 error generated.

Seems this file is well out of date. Suggest the out-of-date instructions should be removed (in the first instance) or updated (ideally).

**Comment by jcacerec** [comment]
I fixed the compile issue (was a problem with the new MacOSX10.11.sdk). You should be able to build from the master branch.
The binary is only included in the release: https://github.com/jcacerec/jacktrip/releases/tag/v1.1. I updated the instructions accordingly.
