### ISSUE TITLE
Can't install jacktrip on OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by lossius** [jcacerec/jacktrip#21]
I just tried installing on El Capitan using the command

`sudo cp jacktrip /usr/bin/`

However this leads to the following error message:

`cp: /usr/bin/jacktrip: Operation not permitted`

I guess this is due to the fact that access to `/usr/bin` has been crippled in 10.11. Probably Jacktrip now need to be installed somewhere in `/usr/local` instead?

**Comment by jcacerec** [comment]
I updated the intall instructions to with /usr/local/bin. Thanks for pointing this out!

**Comment by lossius** [comment]
Thanks. There are no jacktrip binary file present in the src folder in the Git repository itself, so following the commands gave me an error message, but after having downloaded the latest release, cd to the bin folder, and copying that binary to /usr/local/bin according to your commit, it worked fine. Thanks!

**Comment by jcacerec** [comment]
Yes, I should clarify that, the source does not include the binary, only the releases do. I am glad it worked though!
