### ISSUE TITLE
system:playback autoconnection at start

### ISSUE THREAD

**Issue by Rsantct** [jcacerec/jacktrip#25]
Dear team,

I've noticed that JackTrip:receive_X ports are automagically connected to system:playback_X when "jacktrip -c server" is started, if the ports becomes active as per the server end is available.

I'am currently using jacktrip to receive audio into an active DIY loudspeaker management system. The loudspeakers drivers are directly attached to system:playback_X, these ports are managed by Brutefir as a FIR xover and as a loudness compensated volume control. This is the system that I use:

[https://github.com/AudioHumLab/FIRtro](https://github.com/AudioHumLab/FIRtro)

Netjack is not affordable for me because both ends, the sender and the receiver runs Jack over an ALSA backend.

It would be nice if, optionally, jacktrip does not autoconnects to system:playback_X because loudspeakers are not attenuated here, so full power is applied to loudspeaker drivers :-(

Thank you in advance!

Best regards.
Rafael

**Comment by jcacerec** [comment]
Hi Rafael,

If you download the latest git version, there's an option that does exactly that:
--nojackportsconnect

Let me know if it works for you.

All the best!
Juan-Pablo

**Comment by Rsantct** [comment]
Hi Juan Pablo.

I've successfully run the git version on my audio system. 
This is a great and useful software!

Thank you very much!
¡Muchísimas gracias!
Rafael
