### ISSUE TITLE
Latency is not constant

### ISSUE THREAD

**Issue by reduzent** [jcacerec/jacktrip#27]
I noticed that the audio of a jacktrip transmission jumps forth and back by one block size sporadically. Since the procotol is using a sequence number to identify individual packets, it seems to me this jumping could be avoided.

**Comment by jcacerec** [comment]
This is by design: clock drifts are reset after a little while to keep latency constant. What you suggest is a feature that for sure can added by anyone that wants to extend the algorithm.
